CREATE TABLE restaurants (
  restaurantsPriceRange2 int,
  dessert VARCHAR,
  latenight VARCHAR,
  lunch VARCHAR,
  dinner VARCHAR,
  breakfast VARCHAR,
  brunch VARCHAR,
  romantic VARCHAR,
  intimate VARCHAR,
  classy VARCHAR,
  hipster VARCHAR,
  divey VARCHAR,
  touristy VARCHAR,
  trendy VARCHAR,
  upscale VARCHAR,
  casual VARCHAR,
  restaurantsTableService VARCHAR,
  restaurantsGoodForGroups VARCHAR,
  restaurantsReservations VARCHAR,
  restaurantsAttire VARCHAR,
  restaurantsDelivery VARCHAR,
  restaurantsTakeOut VARCHAR,
  caters VARCHAR,
  alcohol VARCHAR,
  hasTV VARCHAR,
  wiFi VARCHAR,
  noiseLevel VARCHAR,
  goodForKids VARCHAR,
  dogsAllowed VARCHAR,
  outdoorSeating VARCHAR,
  businessAcceptsCreditCards VARCHAR,
  wheelchairAccessible VARCHAR,
  bikeParking VARCHAR,
  garage VARCHAR,
  street VARCHAR,
  validated VARCHAR,
  lot VARCHAR,
  valet VARCHAR,
  id INT PRIMARY KEY,
  name VARCHAR,
  neighborhood VARCHAR,
  address VARCHAR,
  city VARCHAR,
  state  VARCHAR,
  postalCode VARCHAR,
  latitude VARCHAR,
  longitude VARCHAR,
  stars VARCHAR,
  reviewCount int,
  isOpen VARCHAR,
  categories VARCHAR,
  monday VARCHAR,
  tuesday VARCHAR,
  wednesday VARCHAR,
  thursday VARCHAR,
  friday VARCHAR,
  saturday VARCHAR,
  sunday VARCHAR
);


CREATE TABLE menus (
  id INT PRIMARY KEY,
  name VARCHAR,
  description VARCHAR,
  category VARCHAR,
  price FLOAT,
  reviewIds VARCHAR,
  photoIds VARCHAR
);